"""
Django settings for epic project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-49s4%ljt&vzo!!32@b3bl(pakp#opuq$(gw894e1nm(t@hq$$f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'billing',
    "defdef",
    "rest_framework"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'billing.middlewares.EpicAuthMiddleware',
]

ROOT_URLCONF = 'epic.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'epic.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# settings.py
EPIC_CONFIG = {
    "BASE_URL": "https://fhir.epic.com/api/FHIR/R4",
    "CLIENT_ID": "978b0df0-9a02-4910-be60-06d597397677",
    "CLIENT_SECRET": "i39405Efo3wOVWAo3UzOhDjSb9fSZtBvysxOQHIRDtXSPxzVSKM10RNJoxPIKTMnVt65G68KCmNpC6shkF+KrA==",
    # "CLIENT_SECRET": "1B1D06B81DC7B08779EC25793313AA17887C8F65",
    "REDIRECT_URI": "https://aef4-202-83-25-55.ngrok-free.app/callback/",
    'EPIC_AUTH_URL': 'https://fhir.epic.com/interconnect-fhir-oauth/oauth2/authorize',
    'EPIC_TOKEN_URL': 'https://fhir.epic.com/interconnect-fhir-oauth/oauth2/token',
    'EPIC_FHIR_URL': 'https://fhir.epic.com/interconnect-fhir-oauth/api/FHIR/R4',
    'AUTH_SUCCESS_URL': '/',
    'REFRESH_TOKEN_LIFETIME_DAYS': 30,
    'TOKEN_RETRY_COUNT': 3,
    'TOKEN_RETRY_DELAY': 1,
}
